### ISSUE TITLE
Kemal version tags don't support semver format

### ISSUE THREAD

**Issue by veelenga** [sdogruyol/kemal#38]
From `shards`' [usage](https://github.com/ysbaddaden/shards/blob/master/README.md#usage):

> When libraries are installed from Git repositories, the repository is expected to have version tags following the [semver](http://semver.org/) format, prefixed with a v. Examples: v1.2.3 or v2.0.0-rc1.

So, currently I can't refer to a specific version of Kemal:

```yaml
dependencies:
  kemal:
    github: sdogruyol/kemal
    version: 0.5.0
```

```sh
$ crystal deps 
Updating https://github.com/sdogruyol/kemal.git
git command failed: git ls-tree -r --full-tree --name-only v0.5.0 -- shard.yml ()
```

Could you please add a support of semver format ?
